MATCH (blogs:BLOGS)
CREATE (b1:BLOG {id: randomUUID(), title: 'abstractions', date: '9th April 2024', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/abstractions.md'})
CREATE (b2:BLOG {id: randomUUID(), title: 'Thoughts on death', date: '19th august 2023', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/thoughts_on_death.md'})
CREATE (b3:BLOG {id: randomUUID(), title: 'Uneasiness in being', date: '14th December 2023', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/uneasiness_in_being.md'})
CREATE (b4:BLOG {id: randomUUID(), title: 'Meme Tree', date: '20th February 2023', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/meme_tree.md'})
CREATE (b5:BLOG {id: randomUUID(), title: 'On Love', date: '17th November 2022', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/on_love.md'})
CREATE (b6:BLOG {id: randomUUID(), title: 'In Defense of Randomness', date: '17th August 2021', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/in_defense_of_randomness.md'})
CREATE (b7:BLOG {id: randomUUID(), title: 'Unvaried Iterations', date: '22nd May 2021', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/unvaried_iterations.md'})
CREATE (b8:BLOG {id: randomUUID(), title: 'Quantifying Information', date: '24th March 2021', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/quantifying_information.md'})
CREATE (b9:BLOG {id: randomUUID(), title: 'Dealing With Absence', date: '17th Jan 2021', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/dealing_with_absence.md'})
CREATE (b10:BLOG {id: randomUUID(), title: "I'm Taking A Break", date: '14th August 2020', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/im_taking_a_break.md'})
CREATE (b11:BLOG {id: randomUUID(), title: 'Futility', date: '24th July 2020', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/futility.md'})
CREATE (b12:BLOG {id: randomUUID(), title: 'More On The Loops', date: '13th July 2020', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/more_on_the_loops.md'})
CREATE (b13:BLOG {id: randomUUID(), title: 'Hello World', date: '07th July 2020', body: 'https://raw.githubusercontent.com/narengogi/chintamani-ui/main/assets/blogs/hello_world.md'})
CREATE (blogs)-[:HAS_BLOG]->(b1)
CREATE (blogs)-[:HAS_BLOG]->(b2)
CREATE (blogs)-[:HAS_BLOG]->(b3)
CREATE (blogs)-[:HAS_BLOG]->(b4)
CREATE (blogs)-[:HAS_BLOG]->(b5)
CREATE (blogs)-[:HAS_BLOG]->(b6)
CREATE (blogs)-[:HAS_BLOG]->(b7)
CREATE (blogs)-[:HAS_BLOG]->(b8)
CREATE (blogs)-[:HAS_BLOG]->(b9)
CREATE (blogs)-[:HAS_BLOG]->(b10)
CREATE (blogs)-[:HAS_BLOG]->(b11)
CREATE (blogs)-[:HAS_BLOG]->(b12)
CREATE (blogs)-[:HAS_BLOG]->(b13)